name: Prepit Deploy

on:
  push:
    branches: [production]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd prepwise
            git pull origin production
            docker compose up -d --build app
            docker compose exec -T app alembic upgrade head

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          generate_release_notes: true
          target_commitish: production
